### ISSUE TITLE
build ios issus

### ISSUE THREAD

**Issue by saifamer2030** [ZEGOCLOUD/zego_uikit_signaling_plugin_flutter#2]
get this issus : 
remark: incremental compilation has been disabled: it is not compatible with whole module optimization error: using bridging headers with module interfaces is unsupported

WHY?!!!!

**Comment by yoer** [comment]
In which Demo did the problem occur?


the minimum version of the third party in the component podspec and podfile should be changed to 11 or above 
try change deploymentInfo to support iOS12 +
 ```Podfile

podfile: 
platform :ios, '12.0' 
 
podspec: 
s.ios.deployment_target = '12.0' 
```

**Comment by yoer** [comment]
the issue has been too long without a reply, so it is closed.
