### ISSUE TITLE
I don't know how to use it, the tutorial is no longer compatible with the sdk.

### ISSUE THREAD

**Issue by YouXianMing** [ZEGOCLOUD/zego_uikit_signaling_plugin_flutter#3]
I refer to the tutorial of  [Quick start (with call invitation)](https://docs.zegocloud.com/article/14826), 
![截屏2023-09-08 09 34 11](https://github.com/ZEGOCLOUD/zego_uikit_signaling_plugin_flutter/assets/5523568/d198e000-e6dd-4d3b-bd6a-14b73dfa7353)
in my project, is 
![截屏2023-09-08 09 36 34](https://github.com/ZEGOCLOUD/zego_uikit_signaling_plugin_flutter/assets/5523568/4e7b98cb-6bef-4b96-8cd9-8276131e47d3)
I think the tutorial is no longer compatible with the sdk, see if you can update the tutorial.

**Comment by yoer** [comment]
![image](https://github.com/ZEGOCLOUD/zego_uikit_signaling_plugin_flutter/assets/11307627/9bf5a8a3-4216-487e-884f-9565f95a3489)
import dart files please

**Comment by YouXianMing** [comment]
I imported the sdk,
![截屏2023-09-08 15 16 24](https://github.com/ZEGOCLOUD/zego_uikit_signaling_plugin_flutter/assets/5523568/ea71dce7-6972-450b-b72a-7431c499db63)

`import 'dart:math';

import 'package:project_base_libs_pkg/base_file_headers.dart';
import 'package:vendor/file_headers.dart';
import 'package:zego_uikit_prebuilt_call/zego_uikit_prebuilt_call.dart';
import 'package:zego_uikit_signaling_plugin/zego_uikit_signaling_plugin.dart';

const int _appId = 00;
const String _appSign = '00';

enum ZegoCallType {
  groupVideoCall,
  groupVoiceCall,
  oneOnOneVideoCall,
  oneOnOneVoiceCall,
}

class CallPage extends StatelessWidget {
  final String callID;
  final String userID;
  final String userName;
  final ZegoCallType type;

  const CallPage({
    Key? key,
    required this.callID,
    required this.userID,
    required this.userName,
    required this.type,
  }) : super(key: key);

  static String testUserId = Random().nextInt(10000).toString();

  @override
  Widget build(BuildContext context) {
    late ZegoUIKitPrebuiltCallConfig config;

    /// 1.1.1 define a navigator key
    final navigatorKey = GlobalKey<NavigatorState>();

    /// 1.1.2: set navigator key to ZegoUIKitPrebuiltCallInvitationService
    ZegoUIKitPrebuiltCallInvitationService(
      appID: null,
      appSign: '',
      userID: '',
      userName: '',
      plugins: [],
      child: Container(),
    ).setNavigatorKey(navigatorKey);

    switch (type) {
      case ZegoCallType.groupVideoCall:
        config = ZegoUIKitPrebuiltCallConfig.groupVideoCall()
          ..onOnlySelfInRoom = (_) {
            Navigator.of(context).pop();
          };
        break;
      case ZegoCallType.groupVoiceCall:
        config = ZegoUIKitPrebuiltCallConfig.groupVoiceCall()
          ..onOnlySelfInRoom = (_) {
            Navigator.of(context).pop();
          };
        break;
      case ZegoCallType.oneOnOneVideoCall:
        config = ZegoUIKitPrebuiltCallConfig.oneOnOneVideoCall()
          ..onOnlySelfInRoom = (_) {
            Navigator.of(context).pop();
          };
        break;
      case ZegoCallType.oneOnOneVoiceCall:
        config = ZegoUIKitPrebuiltCallConfig.oneOnOneVoiceCall()
          ..onOnlySelfInRoom = (_) {
            Navigator.of(context).pop();
          };
        break;
    }

    return Container(
      color: Colors.black,
      child: SafeArea(
        child: ZegoUIKitPrebuiltCall(
          appID: _appId,
          // Fill in the appID that you get from ZEGOCLOUD Admin Console.

          appSign: _appSign,
          // Fill in the appSign that you get from ZEGOCLOUD Admin Console.

          userID: userID,
          userName: userName,
          callID: callID,
          config: config,
          // You can also use groupVideo/groupVoice/oneOnOneVoice to make more types of calls.
          onDispose: () {
            appPrint('onDispose');
          },
        ),
      ),
    );
  }
}
`

![截屏2023-09-08 15 18 17](https://github.com/ZEGOCLOUD/zego_uikit_signaling_plugin_flutter/assets/5523568/26447b92-306a-47cd-90e3-42073ab90543)

Still have the error.

**Comment by YouXianMing** [comment]
![截屏2023-09-08 15 21 10](https://github.com/ZEGOCLOUD/zego_uikit_signaling_plugin_flutter/assets/5523568/adbc7775-43e7-4e8b-8012-529ce1fb32f0)
and it show 'ZegoUIKitPrebuiltCallInvitationService' is deprecated and shouldn't be used.

**Comment by yoer** [comment]
``` yaml
  zego_uikit: ^2.11.0
  zego_uikit_prebuilt_call: ^3.13.5
  zego_uikit_signaling_plugin: ^2.4.0
```
You were using the previous 2.0+ version, please switch to version 3.0+.

**Comment by yoer** [comment]
https://pub.dev/packages/zego_uikit_prebuilt_call/changelog

**Comment by yoer** [comment]
升级版本后解决了吗 大兄弟

**Comment by YouXianMing** [comment]
我试试，和我项目里引用的一些库有版本冲突
