### ISSUE TITLE
can't run command 'flutter pub add zego_uikit_signaling_plugin'

### ISSUE THREAD

**Issue by JameSupphanut** [ZEGOCLOUD/zego_uikit_signaling_plugin_flutter#4]
`Because zego_uikit_signaling_plugin depends on zego_uikit_signaling_plugin, version solving failed.`

error response. how to fix

**Comment by yoer** [comment]
maybe that's your local project problem? i test ok in new project

**Comment by yoer** [comment]
the issue has been too long without a reply, so it is closed.
