### ISSUE TITLE
First time call is disconnected

### ISSUE THREAD

**Issue by piyushlodaliya** [ZEGOCLOUD/zego_uikit_signaling_plugin_flutter#5]
When I do sign up and initiate the first call at that time the call is getting disconnected from the user side. While same configuration is working when I do the call second time. Can anybody help me to sort out this problem?

I had integrated using 'zego_uikit_prebuilt_call' & 'zego_uikit_signaling_plugin'.

**Comment by yoer** [comment]
Could you please provide more specific example code and error messages?

**Comment by yoer** [comment]
the issue has been too long without a reply, so it is closed.
